
version: '3.4'
services:
  
  webapi:
    image: ${DOCKER_REGISTRY-}foodapi

    
    build:
      context: .
      dockerfile: ./Dockerfile

   
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString:Server=sql.bsite.net\\MSSQL2016;Database=tima2006_Lamoda;User Id=tima2006_Lamoda;Password=Tima2006;TrustServerCertificate=true;
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Your_password123"
      - "ACCEPT_EULA=Y"
    container_name: mssql